### PR TITLE
Add s390x support

### PR DESCRIPTION
**Pull request by raulcabello**
we would like make k3d available on s390x. We need confd on s390x as it is needed for building k3d proxy https://github.com/rancher/k3d/blob/main/proxy/Dockerfile#L9

### CODE REVIEW

**Comment by raulcabello** [comment]
@iwilltry42 we would like add support for s390x to k3d. Can you review this PR, please?

**Review by iwilltry42 — APPROVED** [review]

**Comment by iwilltry42** [comment]
Hi @raulcabello , sure!
Thanks for this :+1: 
Somehow I missed the notification for the PR, sorry!

**Comment by raulcabello** [comment]
Thanks @iwilltry42 ! 
Can you create a release, please? so we can use it in k3d. I'll submit a PR to support k3d on s390x

**Comment by iwilltry42** [comment]
@raulcabello done :+1:

**Pull request merged**
